config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :address
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: '投稿に成功しました'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path, alert: '不正なアクセスです'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '更新に成功しました'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :address, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'プロフィールを更新しました'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Okiumi5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= link_to root_path do %>
      <h1>okiumi</h1>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to "ユーザー一覧", users_path %>
      <%= link_to "マイページ", user_path(current_user) %>
      <%= link_to "新規投稿", new_post_path %>
      <%= link_to "ビーチ一覧", posts_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "ユーザー一覧", users_path %>
      <%= link_to "ビーチ一覧", posts_path %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "新規登録", new_user_registration_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @post do |f| %>
  <%= f.label :title, 'ビーチ名' %>
  <%= f.text_field :title %>

  <%= f.label :address, '市・エリア' %>
  <%= f.text_field :address %>

  <%= f.label :body, 'おすすめポイント' %>
  <%= f.text_area :body %>

  <%= f.submit '更新' %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <%= post.title %>
  <% end %>
  <%= post.user.username %>
  <%= post.updated_at.strftime("%Y-%m-%d") %>
<% end %>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_with model: @post do |f| %>
  <%= f.label :title, 'ビーチ名' %>
  <%= f.text_field :title %>

  <%= f.label :address, '市・エリア' %>
  <%= f.text_field :address %>

  <%= f.label :body, 'おすすめポイント' %>
  <%= f.text_area :body %>

  <%= f.submit 'シェア' %>
<% end %>

app/views/posts/show.html.erb
<%= link_to user_path(@post.user) do %>
  <%= @post.user.username %>
<% end %>


<%= @post.title %>
<%= @post.address %>
<%= simple_format @post.body %>

<% if @post.user.id == current_user.id %>
  <%= link_to 'edit', edit_post_path(@post) %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user do |f| %>

  <%= f.label :username, '名前' %>
  <%= f.text_field :username %>

  <%= f.label :email, 'メールアドレス' %>
  <%= f.text_field :email %>

  <%= f.label :profile, 'プロフィール' %>
  <%= f.text_area :profile %>
  
  <%= f.submit '更新' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= link_to user.username, user_path(user) %>
投稿数：<%= user.posts.count %>
<% end %>

app/views/users/show.html.erb
<%= @user.username %>
<%= @user.profile %>

<% if @user.id == current_user.id %>
  <%= @user.email %>
  <%= link_to "edit", edit_user_path(@user) %>
<% end %>

<% @user.posts.each do |post| %>
  
  <%= link_to "詳細", post_path(post) %>
  <% if @user.id == current_user.id %>
    <%= link_to "編集", edit_post_path(post) %>
    <%= link_to "削除", post_path(post), method: :delete, data: {confirm: "削除しますか？"} %>
  <% end %>
<% end %>